# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: audiobooks-pv
# spec:
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteMany
#   persistentVolumeReclaimPolicy: Retain
#   local:
#     path: /data-nfs/audibookshelf/books
#   storageClassName: nfs
# ---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audibookshelf-metadata-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: audibookshelf-metadata-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audibookshelf-config-pv
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: audibookshelf-config-pv

